node3rd-basic/todolist_5th

homework/lee-yeonseo/fn.js
함수는 한가지 일만 하도록 단순하게 만들수록 유지보수에 좋다.
입력받는 값의 타입과 반환하는 값의 타입을 동일하게 하는 것이 좋다.
(반환하는 값의 타입을 다르게 하기 보다는 에러를 발생시키는 게 낫다. throw new Error())
매개변수(파라미터)는 함수 선언 시 함수가 받을 입력 값을 정의하는 변수고, 인자는 함수 호출 시 함수에 전달되는 값이다.
배열 : 변수들이 모여있는 뭉치
find메서드 : 배열이나 객체에서 입력받은 값을 찾는 메서드.  가장 첫번째로 찾은 값을 반환한다.
인자로 콜백함수를 넣고 싶을 때 fn(callback())처럼 괄호를 열어 함수를 실행시키면, 함수가 전달되는 것이 아닌, 함수가 실행된 값이 전달되기 때문에 괄호를 열면 안된다.
=> [이연서/fn_array]함수 종류 및 사용해보기

homework/jinseo_kim/backend/package.json, homework/jinseo_kim/fn.js
배열과 함수의 정의를 정리하고, 함수를 사용하는 연습을 해보았습니다.
- PR의 제목을 기능, 명확한 포인트 또는 키워드로 해야 하는 이유와 내용을 요목조목 잘 정리해야 하는 이유는?
- 배열 Array
- 함수 function
> 내가 알고 있다 라고 말 하는것은 이해한 것을 다른사람에게 설명할 수 있어야 한다. 그래서 배운 내용을 요약하고, 정리하는 습관이 필요하다.
그런데 튜터님께서 말씀하신 것만 정리하면 기억에 의존하기 때문에 아주 대충 정리될 수 밖에 없는데, 본인이 직접 찾아보면서 꼬리에 꼬리를 무는 형식으로 내용을 추가하여 정리하면 아주 좋은 가이드북이 되지 싶다.
또한, 아무리 경력이 많은 튜터님들, 현업을 뛰고 계신 경력많은 분들 이라고 해도 까먹는건 당연하다. 그렇기 때문에 나중에 다시 찾아볼 때를 대비하여 잘 정리하고, 제목, PR, 브랜치 명을 명확한 포인트 또는 키워드로 지정하게 된다면 찾아볼 때도 유용하고, 내용이 바로바로 떠오르고 이해하기에 훨씬 좋다.
- Array 는 이름과 인덱스로 참조되는 정렬된 값의 집합이며 한개의 변수에 여러개의 값을 순차적으로 저장할 때 사용한다.
- 한마디로 과일 이라는 배열에 [ 토마토, 레몬, 사과, 참외 ] 이러한 요소(element) 가 들어있고, 각각의 요소는 0번부터 시작하여 3번까지의 Index 를 가지고 있다.
- 주로 cosnt로 선언한다.
- 배열의 이름은 복수형으로 작성하는데, 코드를 읽는 사람들이 변수가 배열임을 쉽게 이해할 수 있도록 하기 위함이다. 이러한 암묵적인 약속은 코드의 가독성을 높이고 협업 시에도 일관성을 유지하는 데 …
=> [김진서/fn_array] 2024-05-24 수업내용 정리 및 배열, 함수 정리와 연습문제 풀이

homework/goonamuk/3rd_func_hw.js
* 미지수를 받아서 지정한 로직을 실행하는 코드
```
const 상수이름 = function( ) {
return 구동 로직
};
```
* 호출 :
```
상수이름( 로직에 넣을 미지수 );
화살표함수 : 함수를 간소화시킨 것
const 상수이름 = (미지수) => {
return 구동 로직();
};
```
* 내부에 return문 외에 다른 로직이 없다면 return과 중괄호 생략 가능
* 미지수가 하나 뿐이라면 미지수 겉의 소괄호 생략 가능
* 되도록 한 함수는 하나의 기능만 수행하도록 구성(간결하게)
* 함수의 이름은 그 기능을 반영하도록 구성(명확하게)
* Callback 함수
* 다른 함수의 인자(미지수)에 할당된 함수
* 단, 콜백함수를 다른 함수의 인자로 넣을 때 처리결과를 넣으려면, 그 처리결과 역시 함수여야 한다.
```
예시 : 
const 함수3 = function ( int ) {
return int * 10;
};
const 함수2 = function ( int ) {
return 함수3(int) % 2
};
const 함수1 = function ( int ) {
return 함수2(int) +1
};
console.log(함수1(2)) → 1
```
* .find
* arr.find(조건); → 해당 조건에 부합하는 인자를 찾아옴
arr.find(함수)일 때는?  →  그 함수를 실행한 결과에 부합하는 인자를 찾아옴
* .map
* .filter
함수에 대한 보다 깊은 이해
화살표 함수의 축약 방법
배열.find(조건문)으로 for문을 돌린 것과 같은 효과를 내는 방법 …
=> [구남욱/fn_array] 함수 연습

homework/hyunwoo/fn.js
배열에서 find함수 사용해보기
< 함수(Function) >
- 어떤 처리를 반복적으로 수행하도록 만든 코드 뭉치
- 함수를 사용 하는 이유 : 코드의 반복적인 사용의 편리함을 위해
- 함수 이름은 알아보기 쉽게 만든다.
- 함수 내용은 단순하게 하고 한가지 작업만 하도록 한다.
(다양한 return일 경우 함수를 분리하는 것이 좋다.)
- 함수의 값을 반환받기 위해서는 return 작성이 필요함
- void 함수 : 반환값이 없는 함수
- 함수의 결과는 같은 타입으로 하는것이 좋다.
(타입이 다르면 의도와 다른 결과를 도출할 수 있음)
< 화살표 함수 >
const 함수이름 = ( 변수 ) => {
return 함수식;
};
- return만 있는 경우 return 과 { } 생략 가능
const 함수이름 = ( 변수 ) => 함수식;
- 변수가 1개면 ( ) 생략 가능
const 함수이름 = 변수 => 함수식;
< 콜백 함수 >
- 다른 함수의 매개변수로 전달되어 수행되는 함
- 주로 사용하는 onclick 함수가 콜백 함수
- 자바스크립트는 싱글스레드인데 비동기 작업을 위해 콜백 함수를 사용함
- 콜백 함수를 남발하면 함수가 계속 쌓이는 콜백지옥이 발생함
- async, await를 사용하여 콜백지옥을 해결할 수 있다.
< find 함수 >
- 배열에서 특정 조건을 만족하는 첫번째 요소를 반환하는 함수
- 반환값이 없으면 Undefined를 반환
- 원하는 특정 요소를 찾는데 유리함
- Object에서 특정 값을 가지고 검색할 수 있다.
- 함수의 사용방법을 알 수 있었습니다.
- 화살표함수를 …
=> [이현우/fn_array]함수, 배열, find함수

homework/jeon-suwon/fn.js
함수의 정리
함수의 활용
find ( ) 메서드의 활용
1.선언식
function funcA() {
console.log("함수A가 호출됨");
}
2.표현식
const funcB = function () {
console.log("함수B가 호출됨");
};
3.화살표함수
const arrowfunc = () => {
console.log("화살표 함수가 호출됨");
};
3가지 전부 활용은 비슷하지만 선언식과 표현식에서는 호이스팅 부분에서 조금 다르고, 화살표함수에서는 this부분이 들어가면 조금 달라지는 부분이 있다.
함수의활용 - 함수안에 함수, callback 함수
함수안에함수
function sumB(value1, value2, value3 = 5) {
const result = value1 + value2;
const multiA = (a, b) => a * b;
return multiA(result, value3);
}
const resultB = sumB(1, 2, 3);
함수안에 함수를 넣어서 이 하나의 코드로만 본다면 귀찮아 보이지만 엄청 많아지면 의미 있는 작업 단위로 모듈화하여 프로그램을 분할 작성함으로써, 간결하고 이해하기 쉬운 프로그램을 만들 수 있고 여러곳에서 반복을 하지않고 , 함수로 정의하여 동일코드를 중복으로 작성을 하지 않을 수있다. 그러므로써 재사용에 용이하다.
Find()의 활용
const Data = {
movie: [
{ id: 1, name: "영화1", 개봉일: "2024-05-11" },
{ id: 2, name: "영화2", 개봉일: "2024-05-12" …
=> [전수원/fn_array] 함수(function), map 정리 및 활용

homework/jeon-suwon/backend/app.js, homework/jeon-suwon/fn.js, homework/jeon-suwon/sample.js
JSON으로 응답하는 이유
JSON이 경량이고 읽기 쉬운 표준 데이터 형식으로, JavaScript에서 쉽게 파싱되고 사용될 수 있기 때문이다. 또한, JSON은 대부분의 프로그래밍 언어에서 호환되며, 네트워크 트래픽을 줄이고 응답 속도를 높이는 데 도움이 됩니다. JSON은 브라우저 호환성이 뛰어나고 사람이 읽고 쓰기 쉬운 형식이기 때문에 디버깅과 로그 분석에도 유리합니다.
API를 정하는 이유 
개발 과정의 효율성과 일관성을 높이고, 품질을 보장하며, 명확한 커뮤니케이션과 협업을 촉진하기 위해서 사용한다..
map() 메서드
배열 내의 모든 요소 각각에 대하여 주어진 함수를 호출한 결과를 모아 새로운 배열을 반환하는 메서드이다.
ex)
```
const arr = ["a", "b", "c", "d"];
const newarr = arr.map((el, index) => [el, index]);
[['a', 0], ['b', 1], ['c', 2], ['d', 3]]
```
**map은 메서드를 호출한 배열의 길이 만큼의 새로운 배열을 만들어내는 게 핵심인데, 콜백 함수의 return 값을 통해 새로운 배열들의 각 요소를 변형할 수 있다는 특징이 있는 것이다.**
ex) 
```
const arr = ["a", "b", "c", "d"];
const newarr = arr.map((el) => el);
console.log(arr); // ["a", "b", "c", "d"]
console.log(newarr); //["a", "b", "c", "d"]
console.log(arr === newarr); …
```
=> [전수원/read-api-sample]RestAPI정리, map,filter활용, 구조분해할당

homework/hyunwoo/backend/app.js, homework/hyunwoo/backend/package.json, homework/hyunwoo/mapFilterSpread.js
- map 함수
Array.map(조건) 형식으로 사용한다.
원본 배열은 변경하지 않고 배열에 있는 모든 요소를 변경하여 같은 크기의 새로운 배열을 만들 때 사용한다.
새로운 배열을 생성하기 때문에 원본 배열은 변경되지 않는다.
- filter 함수
Array.filter(조건) 형식으로 사용한다.
배열의 요소를 순회하면서 조건에 맞는 요소를 찾아서 배열을 만들 때 사용한다.
조건에 맞는 요소가 없으면 빈 배열을 반환한다.
- 스프레드 연산자
[ ...Array ] 형식으로 사용한다.
배열을 풀어서 넣을 때 사용한다.
배열을 복제하거나 병합할 때 사용하기 좋다.
배열을 복제한 후 원본 배열과 비교하면 false를 반환한다.
(배열은 같지만 각각 데이터 주소가 다르다.)
- find 함수와 filter 함수
find 함수와 filter 함수 모두 조건에 맞는 요소를 찾을 때 사용할 수 있다.
find 함수는 조건에 맞는 첫번째 요소만 반환하고
filter 함수는 조건에 맞는 모든 요소를 반환한다.
그러면 filter 함수만 사용하면 되지 않을까? - No
filter 함수를 사용하게 되면 하나의 요소만 찾는 경우에도 모든 요소를 순회하기 때문에
불필요한 작업이 실행되어 실행 효율성이 떨어질 수 있다.
그래서 조건에 맞는 한가지 요소만 찾을 경우에는 find 함수를 사용하는 것이 좋다.
- CRUD
컴퓨터 소프트웨어가 가지는 기본적인 데이터 처리기능
Create(생성), Read(읽기), Update(수정), Delete(삭제)
- REST
REST = Representational State Transfer의 …
=> [이현우/read-api-sample] map, filter, 스프레드 연산자 사용해보기 / 할일 목록 조회, 할일 상세 조회 API 구현하기

homework/seojin/backend/app.js, homework/seojin/mapFilterSpread.js
map, filter, spread 사용 방법과 json 형태로 응답하는 이유, 그리고 restAPI
-map
const 베이직반_공주머니 = 공주머니 .map(공 => 공 === "초록공" ? 공 + "_챌린지반" : 공 + "_베이직반"
-filter
const 베이직반_공주머니 = 반표기된_공주머니.filter(공 => {
if(공.includes(베이직반){
return tue
}else{
return fales
}
-json 형태로 응답하는 이유
프론트엔드와의 원활한 협업을 위해 형태 없는 문자가 아닌 약속된 json이란 형태로 작성된 응답값을 내려주는 것이다.
-restAPI
REST는 REpresentational State Transfer의 약자이다. 그리고 분산 하이퍼 미디어의 아키텍처 스타일이기도 하다.
즉 REST 는 프로토콜이나 표준이 아닌 스타일 아키텍처라는 말이다. (그렇다면 굳이 사용하지 않아도 된다는 뜻일까?)
이런 REST 에도 원칙과 제약 규칙이 있는데 이 REST 아키텍처 스타일을 따르는 웹 API(또는 웹 서비스)를 REST API(또는 RESTful API)라고한다.
균일한 인터페이스
​
-구성 요소 인터페이스에 일방석의 원칙을 적용함으로써 전체 시스템 아키텍처를 단순화하고 상호작용의 가시성을 향상시킬 수 있다.
복잡할 것을 간단하게 만들어 이해하기 쉽게 만들어 준다는 이야기 같다.
​
2.클라이언트 서버
​
서버 디자인 패턴은 문제를 분리하여 클라이언트와 서버 구성 요소가 독립적으로 발전하는 데 도움이 된다.
사용자 인터페이스 문제(클라이언트)와 데이터 스토리지 …
=> [박서진/read-api-sample] map, filter, spread 연습해보기/ API 구성해보기

homework/leegilhyeon/backend/app.js, homework/leegilhyeon/backend/package.json, homework/leegilhyeon/fn.js, homework/leegilhyeon/sample.js
`map과 filter`
- map은 배열안에 값들을 특정 조건을 추가하여 복제하는 것으로 기존 배열을 사라지지 않고 유지됩니다. 조건에 맞는 값이 없는 경우에는 undefinded가 반환됩니다.
- filter는 배열안에 요소에 대하여 주어진 조건의 결과값이 true인 요소를 모아 새로운 배열을 반환하는 메서드입니다. 
-map은 내부 함수의 리턴값이 문자, 숫자, 배열 등으로 다양한 타입이 가능하지만 filter는 boolean 타입만 반환합니다.
`스프레드 연산자 (...)`
- 기존 배열을 새로운 배열안에 나열해준다. 스프레드 연산자를 사용하여 기존 배열의 요소를 새로운 배열에 포함시킬 수 있습니다
`api명세서와 json`
- api 명세서를 정해두면, 개발자들은 규칙에 따라 일관된 방식으로 데이터를 처리할 수 있게 된다. 
- 예를 들어 REST api를 설계할 때 http 메소드 사용 규칙을 명확히 하면, 어떤 상황에 어떤 메소드를 사용해야 하는지 명확해 지고, 데이터가 추가되거나 변경되면 규칙에 따라 변경될 수 있도록 로직을 구현할 수 있게 된다.
- Json을 잘 이해하고 사용할 줄 안다면 다양한 시스템과 데이터 교환을 원활히 할 수 있다. 또한,  json은 이해하기 쉽고 사용하기 편리하여 api 응답 형식으로 json을 사용함으로써 데이터를 더 빠르고 효율적으로 처리할 수 있다.
명확하게 개념 이해하고 넘어가지 않았던 부분들을 직접 작성해보면서 이해할 수 있었습니다.
json을 사용하고 api명세서를 작성하는 이유를 알게 되었습니다.
=> [이길현/read-api-sample] map,filter,스프레드연산자 연습하고 할일목록조회와 할일검색 API 만들기

homework/najiyoon/backend/app.js, homework/najiyoon/backend/package.json, homework/najiyoon/backend/yarn.lock
```요청문서```
요청할 때 요청문서에는 req.body : 바디에 담아서 요청하는 것과
url에 키, 벨류로 값을 전달하는 : 쿼리스트링 
여기서 나온 키 = 벨류
v=-2sDZri3y6s
&
list=PLraqxKY_jbi6eM6ULZGItII6sAkb88A6C
&
index=13
=> 여기서 키는 v, list, index 가 되고 = 뒤는 벨류로 되어있음
+
/:에 키 형태로 값을 전달하는 : url 파라미터가 있음
처음에 나온 body에는 다른 2가지와 달리 많은 양을 담아 보낼 수 있으며 json 문자열을 object 형태로 전환하여 바디에 담아준다고 한다. 
또한 json을 활용하기 위해 app.use(express.Json()) 를 사용함
```구조분해할당 예시```
const person ={“name”:”najinaji”, “age”:”22”, “job”:”tutor”}
요청할 때마다
person.name
person.age 등 매번 person을 붙여야하므로
Const {가져오고싶은 name,age} = person
=> name이란 변수에 들어감
선언 후 name이면 najinaji부를 수 있음 
```아이디에 번호넣기```
그냥 Id = todoitems.length+1 하면
중간 삭제 시 번호가 다시 지정됨
1,2,3,4,5 -> 새 목록 -> 1,2,4,5,6 이 아닌 1,2,3,4,5(새거)
Id = todoitems[todoitems.length-1] +1
1,2,3,4,5 -> 새목록 -> 1,2,4,5,6(새거)
위와 같은 방법의 문제점… 하나도 없을 경우 언디파인드
하나 …
=> [나지윤/register-todo-item]할일 api 구현 및 요청방법 3가지

homework/eyohan/fn.js
함수 : 특정 작업을 수행하는 코드 블록
함수 잘 만드는 법 : 가능한 짧게 유지, 함수는 하나의 작업만 수행, 함수의 역할을 설명하는 명확한 이름
함수 선언 : 특정 작업을 수행하는 코드를 묶어 재사용
함수 선언문 : function 키워드를 사용하여 이름이 있는 함수를 정의.
ec) function add(a, b) {
return a + b;
}
함수 표현식 : 함수를 변수에 할당하여 정의
ex) const add = function(a, b) {
return a + b;
};
함수 이름: 함수 선언 시 지정하는 이름, 함수 호출 시 사용.
ex) function hi() {
console.log("Hello");
}
// 함수 이름은 "hi"
변수: 값을 저장하는 데 사용되는 컨테이너.
ex) let number = 5;
const name = "John";
익명 함수: 이름이 없는 함수, 일회성 함수 또는 함수 표현식으로 사용.
ex) const add = function(a, b) {
return a + b;
};
콜백함수 : 다른 함수의 인수로 전달되어 그 함수 내에서 호출되는 함수, 비동기 작업 처리, 이벤트 처리 등.
ex) function fetchData(callback) {
// 데이터 가져오기
callback(data);
}
fetchData(function(data) {
console.log(data);
});
배열 : 여러 값을 하나의 변수에 저장할 수 있는 자료 구조
ex) const numbers = [1, 2, 3, 4, 5];
const fruits = ["apple", …
=> [이요한/fn_array] 수업내용, 함수 정리 및 활용, find 활용 & 복습, 연습문제 풀어보기

homework/eyohan/backend/app.js, homework/eyohan/sample.js
map: map 함수는 배열의 각 요소에 대해 주어진 함수를 호출하고, 그 결과로 새로운 배열을 반환합니다. 이 새로운 배열은 각 요소에 함수를 적용한 결과로 구성됩니다. 주로 배열의 각 요소를 변환하고자 할 때 사용됩니다.
filter: filter함수는 주어진 함수의 반환 값이 true인 요소만을 가지고 새로운 배열을 만듭니다. 이 함수는 배열에서 특정 조건을 만족하는 요소만을 필터링할 때 유용합니다.
스프레드 연산자: 스프레드 연산자는 배열이나 객체를 펼쳐서 개별 요소로 나열하거나 복사하는 데 사용됩니다. 배열에서 사용할 경우 배열을 복사하거나 다른 배열에 추가할 때 유용하며, 객체에서 사용할 경우 객체를 복사하거나 새로운 객체를 생성할 때 사용됩니다.
CRUD 
1. Create : Create는 새로운 데이터를 생성하거나 추가하는 작업을 의미합니다
2. Read : Read는 데이터를 조회하거나 읽는 작업을 의미합니다.
3. Update : Update는 데이터의 내용을 변경하거나 업데이트하는 작업을 의미합니다.
4. Delete : Delete는 데이터를 삭제하거나 제거하는 작업을 의미합니다.
REST :  서비스에서 주로 사용되며, 클라이언트와 서버 간의 통신을 위한 규칙과 제약을 정의합니다. REST 아키텍처는 간단하고 확장 가능하며, 여러 다른 클라이언트와 통신할 수 있는 표준화된 방법을 제공합니다.
*주요특징*
자원 (Resources): 모든 자원은 고유한 식별자인 URI(Uniform Resource Identifier)를 갖습니다. 클라이언트는 이러한 URI를 통해 자원을 식별하고 …
=> [이요한/read-api-sample] map, filter, spread 연습 및 api

homework/jinseo_kim/backend/app.js, homework/jinseo_kim/backend/package.json, homework/jinseo_kim/backend/yarn.lock
- How to “Solv Git Conflict” and “Delete Branch”
- 프론트엔드(Frontend) 와 백엔드(Backend)
- CORS 문제!
- Client가 값을 전달하고, Backend 가 값을 받는 방법
- app.get / app.post 활용하기
Git으로 협업을 하다보면 Conflict (충돌)을 만나게 되거나, Branch를 삭제해야 되는 일이 발생한다. 
우선, 브랜치를 잘못 만들었는데, PUSH까지 해버렸다면 삭제하는 방법은 아래와 같다.
```jsx
git branch -D jinseo_KIM-register-todo-item
// 로컬 브랜치를 강제로 삭제한다
git push origin --delete jinseo_KIM-register-todo-item
// 원격 브랜치를 삭제한다.
```
보통의 경우, 각자 기능 브랜치를 생성하여 기능개발을 할 것이고, 그렇다면 본인이 개발중인 기능에 대해서는 충돌이 없을 것이다.
그러나, A라는 기능을 사람1과 사람2가 같이 작업을 하다보면 반드시 충돌을 만날 것이다.
이럴경우 Git에서는 충돌을 해결하라고 띄울 것이다.
VS Code 에서 확인해보면 수신받은 코드와, 로컬 에서 작업중이던 코드가 둘다 보이게 된다. 
여기서, 필요한 코드만 남겨놓으면 충돌 해결!
기존에 작성한 /homework/backend/app.js 를 띄우고, /frontend/index.html 을 열어보자.
어라? 내가 작성했던 todo list가 호출이되지 않는다. 무슨일??
```jsx
// script/script.js
async …
```
=> [김진서/register-todo-item] How to Solv Git Problem, CORS, RES/REQ, 할일 목록/상세조회/할일생성

homework/lee-yeonseo/backend/app.js, homework/lee-yeonseo/backend/package.json, homework/lee-yeonseo/backend/yarn.lock
>요청자가 값을 전달 하고 백엔드 프로그램이 값을 받는 3가지 방법
1. body
주로 post, put, patch 메서드와 함께 사용된다.
요청의 본문에 데이터를 포함시켜서 전달한다.
body로 전달받은 json데이터를 읽기 위해서는 app.use(express.json())라는 미들웨어를 등록해야 한다.
대량의 데이터를 전달하거나 보안이 필요한 경우 주로 사용된다.
2. params
주로 get 메서드와 함께 사용된다.
URL에 데이터를 포함해 전달한다.
특정 사용자의 정보나 특정 아이템을 가지고 올 때 주로 사용된다.
직관적이다.
ex) /todo-itmes/1
3. query
URL의 쿼리 스트링에 데이터를 포함시켜서 전달한다.
URL의 끝부부에 ?key=value의 형태로 작성한다.
여러개의 데이터를 쉽게 전달할 수 있다.
검색 기능에서 필터링을 할 때나, 정렬 기준을 줄 때 주로 사용된다.
&을 사용해서 여러 조건을 연결할 수 있다.
ex) /todo-itmes?sort=asc&status=done
>배열에 todoItem객체를 추가할 때 겹치지 않는 id값을 주는 방법
- todoItems 배열의 길이를 id값으로 준다면, 만약 중간에 하나가 삭제되었을 때 꼬일 수 있다.
- todoItems배열의 가장 마지막 객체의 id값에 +1을 해주면 중간에 한개가 삭제된다고 하더라도 상관없이 유일한 id값을 가질 수 있다.
- 하지만 만약 todoItems 배열에 아무런 값이 들어있지 않다면 undefined가 나오게 되므로 이를 대비하기 위해서 기본값을 주어야한다.
- ex) const …
=> [이연서/register-todo-item] 할일 생성 api/ 백엔드 프로그램이 값을 받는 방법

homework/leegilhyeon/backend/app.js, homework/leegilhyeon/backend/package.json, homework/leegilhyeon/backend/yarn.lock
**1. 쿼리스트링(QueryString)**
- 쿼리스트링은 url의 일부로 ?뒤에 key=value 로 데이터를 전달합니다.
```
(예시) https://www.example.com/search?영화카테고리=스릴러
node.js에서 값을 받는 방법 - req.query
```
- 쿼리스트링 방식은 주로 Get 요청에서 사용되며 데이터를 조회하거나 검색할때, 페이징할 때 사용됩니다.
- URL에 포함되기 떄문에 사용자가 URL을 저장하거나 공유하기 쉬우며 간단한 데이터 전달에 유용하다는 장점을 가집니다.
**2. URL파라미터(URL Parameters)**
- url 파라미터는 url의 경로 일부로 사용되며 : 뒤에 키를 사용하여 사용합니다.
```
(예시) https://www.example.com/movies/:movieid
node.js에서 값을 받는 방법 - req.params
```
- 주로 특정 리소스를 식별하여 접근할 때 사용하거나 RESTful API 설계시 자주 사용됩니다.
- url 파라미터 사용시 리소스를 명확히 식별할 수  있다는 장점을 가집니다.
- url 구조가 고정되어 있어 복잡한 데이터 전달에는 어려우며 한정된 데이터만 전달합니다.
**3. Body(Request Body)**
- Body는 http 요청 본문에 데이터를 포함하여 전송합니다. JSON, XML, 폼데이터 등 다양한 형식으로 데이터를 포함 할 수 있습니다.
```
{
"title" : "해리포터"
"content" : "재밌습니다."
}
node.js에서 값을 받는 방법 - …
```
=> [이길현/register-todo-item]수업정리(서버와 클라이언트 간의 데이터 전달 방식 , 구조분해할당)와 할일목록생성, 할일목록추가 api구현

homework/goonamuk/backend/app.js, homework/goonamuk/backend/sample.js
api를 넘기는 세 가지 방법
req.body : 
body에 정보를 담아 json으로 넘기는 방법
JSON은 string이므로 객체 변환 필요
코드 위에서
app.use(express.json());를 선언해야 함 <<이거 적어두고 app.use(express.json()) 안 한 사람 나야 나...
query string : 
URL?key=value&key1=value1 형식
req.query 
query parameter는 다음과 같은 형식으로 URL에 나타난다.
URL/value/value1?key=value&a=b
예시 : 
req.params
param은 url/:keyName 형식으로 사용
localhost:3000/games/:game_id
req.params으로 해당 데이터를 받아옴
구조 분해 할당
obj, arr의 내부 value를 외부에서 가져오는 방법
예시 : 
name, genre, launch, maker는 원래 games arr 내에 있는 obj의 keyName
하지만 body에서 게임 이름, 장르, 런칭일자, 제조사를 입력하는 걸 받아오도록 api를 짰다면...
req.body를 통해 새로 const로 name, genre, launch, maker에 새로운 값을 할당 가능
※잠깐※
const는 상수를 선언(상수 : 값과 이름이 변하지 않도록 선언한 것)
그런데 어떻게 이미 전역에서 선언된 const의 값이 다시 설정될 수 있었는가??
이건 javascript의 memory 할당 방식에 따른 것.
const는 이름을 상위 memory에, 값을 하위 memory에 할당함. 이 …
=> [구남욱/register-todo-item]FE-BE 간 데이터 전달(CRUD), 구조분해할당

homework/lee-yeonseo/backend/app.js, homework/lee-yeonseo/backend/package.json, homework/lee-yeonseo/backend/yarn.lock, homework/lee-yeonseo/splice.js
>splice() 메서드
- 자바스크립트 배열에서 요소를 추가하거나 제거 또는 교체하는 메서드.
- 원본 배열을 직접 변경한다.
- 원본배열을 바꾸지 않으면서 splice 메서드를 쓰고 싶다면 [...arr].splice()처럼 스프레드 연산자를 활용하자.
- splice(start, deleteCount, item)
start : 시작 요소 인덱스 / deleteCount : 삭제할 요소의 개수 / item 추가하거나 수정할 요소의 내용
- 만약 삭제할 요소의 개수를 입력하지 않았을 경우에는 시작 인덱스의 요소부터 마지막 요소까지 모두 삭제한다.
- 요소를 삭제하지 않고 추가만 하고 싶다면 삭제할 요소의 개수를 0으로 입력하면 된다.
- 시작 요소의 인덱스가 음수일 경우 배열의 끝에서부터 센다
- splice메서드를 이용하여 배열 내 객체의 일부를 수정하고 싶을 때
객체 내부의 모든 키와 밸류를 작성할 수도 있지만, 그것보다는 해당 객체를 찾아서 변수에 할당한 후, 스프레드 연산자로 풀어주고 수정할 키와 밸류만 적어주면 된다.
>status code
200번대의 코드는 요청이 잘 처리되었을 때.
400번대의 코드는 클라이언트가 잘못된 요청을 했을 때.
500은 서버에서 예기치 못한 오류가 발생했을 때.
splice 메서드
status code
=> [이연서/remove-modify-todo-item] splice 메서드, 할 일 수정/삭제 api

homework/najiyoon/backend/app.js
```...```
스프레드 오퍼레이트
Const a = [1,2,3,4]
…a = 1,2,3,4 로 펼치는 것
[…a] = [1,2,3,4]
```배열에서 삭제하는 방법```
splice 
ex) Const 공주머니 = [
{id:1, “색상”:”빨간색”,  “크기”:”10cm”},
{id:2, “색상”:”주황색”,  “크기”:”16cm”},
{id:3, “색상”:”파랑색”,  “크기”:”12cm”},
{id:4, “색상”:”초록색”,  “크기”:”15cm”},
]
에서 특정 하나 버리고 싶을 때
공주머니.splice(2, 1) 2번째꺼 부터 1개 삭제 
console.log(공주머니)
=>
[
{id:1, “색상”:”빨간색”,  “크기”:”10cm”},
{id:2, “색상”:”주황색”,  “크기”:”16cm”},
{id:3, “색상”:”초록색”,  “크기”:”15cm”},
]
```문제점```
지워질 공 아이디는 계속 바뀔 변수 이므로 splice(index, 몇개 삭제할건지)
의 인덱스에 
공주머니.splice(2, 1) 대신
공주머니.splice(지워질 공 index, 1)
=> findIndex로 내가 원하는 요소 찾기
각각 공을 한번씩 꺼내볼 거고, 그 아이디가 지워질 공 아이디와 같다면 인덱스를 가져옴
Const 지워질 공 index = 공주머니.findIndex(공 => 공id ===지워질 공id)
즉 배열에서 삭제 하고 싶으면 그 배열에 내가 원하는 요소의 인덱스를 알아야함. 값이 아님 :)
```인덱스를 찾지못했을 경우```
index = -1 이 나오므로 맨 뒤에 있는 것을 지움. …
=> [나지윤/remove-modify-todo-item]할일 수정, 삭제 / spilice

homework/songsamuel/backend/app.js, homework/songsamuel/backend/package.json, homework/songsamuel/backend/yarn.lock, homework/songsamuel/mapFilterSpread.js
ex) const arr = [1]
arr.push(2)
arr = [1 , 2]
이런 식으로 배열에 요소를 하나 추가 할 때 push 메서드를  사용하여 추가한다.
즉 get 함수 안에서 정의된 함수는 post함수에서 똑같이 사용할 수 없다.
만약 사용하고 싶다면 get 함수 안에서 정의할 것이 아닌 **전역함수**로써 함수 밖에서 정의하여야 한다.
통신은 요청과 응답으로 되어있다.
요청서와 응답문서를 받는다. 
요청서와 응답문서는 header와 body로 이루어져 있다.
요청 할 때는 req.header / req.body 
응답 할 때는 res.header / res.body 
1. url에 넘긴다.
주소 값 = todo-items/:id
- URL에 key/value 형태로 값을 전달    todo-items  = (key) / :id = (value) 모습
node.js에서 값을 받는 방법은 req.params이다.
2. 쿼리 스트링에다가 넘긴다.
주소 값 = http://localhost:3000/todo-items?key=value
= http://localhost:3000/todo-items?key=value&a=b
consol.log(req.query)를 찍었을 때 { key : ‘value’ } / { key : ‘value’, a: ‘b’ } 
이런 모습으로 나온다.
app.post(‘/todo-items/:a/:b/:c)의 형태로 코드를 작성했을 때 주소창의 모습이 
http://localhost:3000/todo-items/안녕/난/준호?key=value 와 같이 되어있다면 …
=> [송사무엘/register-todo-item] 객체 구조 분해 할당 및  데이터 전달 방식 / 할일 목록 조회 및 추가 api 작성

homework/leegilhyeon/backend/app.js
- **splice() 메서드**는 배열 객체에 사용할 수 있는 내장 메서드로 기존 요소를 삭제또는 교체하거나 새 요소를 추가하여 배열의 내용을 변경합니다.
```
ex) 배열에서 원하는 요소 삭제 하기
const arr1 = [ 사과, 바나나, 수박, 딸기]
arr1.splice(2, 1) // [수박] => 삭제되는 요소를 반환합니다.
console.log(arr1); // [사과, 바나나, 수박, 딸기]
ex)배열에서 요소를 제거 하고, 원하는 위치에 다른 값을 넣기
const arr2 = [사과, 바나나, 수박, 딸기]
arr2.splice(2, 2, 망고, 체리) //[수박, 딸기] => 삭제되는 요소 반환
console.log(arr2); // [사과, 바나나, 망고, 체리]
```
- **indexof() 메서드**는 문자열이나 배열에서 원하는 특정 요소를 검색하고 해당하는 요소의 첫 번째 인덱스를 반환합니다. 만약 일치하는 값이 없다면 -1을 반환합니다.
```
const a = 'hello world'
str.indexof('w') // 6 => w가 위치한 인덱스를 반환합니다.
str.indexof('a') // -1 => 해당 문자열에는 a가 존재하지 않기 때문에 -1 을 반환합니다.
const arr1 = [ "사과", "바나나", "수박", "딸기"]
const index = arr1.indexof("수박")
console.log(index) // 2 =>"수박"에 해당하는 인덱스를 검색하여 2를 반환함.
```
-**findIndex() 메서드**는 특정 조건을 만족하는 요소를 찾아 …
=> [이길현/remove-modify-todo-item] 할일 수정과 할일 삭제 api 작성해보기, 수업내용정리(splice, indexof, findindex)

homework/hyunwoo/backend/app.js, homework/hyunwoo/backend/package.json, homework/hyunwoo/backend/yarn.lock
< JWT란? >
- 인증에 필요한 정보들을 암호화시킨 JSON 토큰
- JWT기반 인증은 JWT토큰을 HTTP 헤더에 실어 서버가 클라이언트를 식별하는 방식
< JWT 구조 >
- Heder: JWT에서 사용할 타입과 해시 알고리즘 종류
- Payload: 서버에서 첨부한 사용자 권한 정보 및 데이터
- Signature: Header와 Payload를 인코딩한 전자서명
< JWT 장점 >
- 데이터 위변조를 막을 수 있음
- 인증 정보에 대한 별도 저장소가 필요없음
- 토큰 기본정보와 서명 등 정보를 자체적으로 지니고있음
- 서버가 무상태로 유지되어 확장성에 유리
- 다른 로그인 시스템에 접근 및 권한 공유가 가능
- 소셜 계정을 이용하여 로그인 가능
- 모바일 어플리케이션에서도 사용 가능
< JWT 단점 >
- 토큰 자체에 정보가 있으므로 유출 시 큰 사고발생
- 토큰 길이가 길어질수록 네트워크 부하 발생
- Payload를 디코딩하면 데이터 확인 가능
- 토큰 자체를 탈취당하면 대처하기가 어려움
< Access Token & Refresh Token >
- JWT 탈취 위험을 대비하기 위해 이중으로 나누는 인증 방식
- Access Token: 클라이언트가 갖고있는 실제로 유저의 정보가 담긴 토큰 요청이 오면 해당 토큰 정보를 활용하여 응답
- Refresh Token: 새로운 Access Token을 발급해주기 위해 사용하는 토큰으로 데이터베이스에 유저 정보와 같이 기록  
감사합니다!
=> [이현우/auth] 회원가입/로그인 API 구현하기, JWT 발급 및 검증하기

homework/seojin/backend/app.js
배열에서 요소를 삭제하는 방법
-splice
1. 검은색의 공주머니를 삭제하고 싶을 경우
const 공주머니 = [
{id: 1, "색상":"빨간색", "크기" :"11cm"},
{id: 2, "색상":"파란색", "크기" :"14cm"},
{id: 3, "색상":"검은색", "크기" :"10cm"},
{id: 4," 색상":"초록색", "크기" :"8cm"},
]
공주머니.splice(2, 1)
console.log(공주머니)
* index로 따졌을때 검은색 공주머니의 순서는 2, 하나만 삭제하려고 하기 때문에 1.
**문제점: 더 많은 공주머니가 있을 경우에는 일일이 순서를 세서 위치를 알아낼 수 없음
2. index를 이용하여 첫 번째 방법의 단점을 보안
* 공주머니의 index id에 따라 지워지는 공이 정해짐
const 지워질_공_id = 3
const 공주머니 = [
{id:" 1 ", "색상":"빨간색", "크기" :"11cm"},
{id:" 2 ", "색상":"파란색", "크기" :"14cm"},
{id:" 3 ", "색상":"검은색", "크기" :"10cm"},
{id:" 4 "," 색상":"초록색", "크기" :"8cm"},
]
const 지워질_공_index = 공주머니.findIndex(공 => 공.id === 지워질_공_id)
console.log("지워질_공_index", 지워질_공_index)
공주머니.splice(지워질_공_index, 1)
console.log("검은공 없는 주머니", 공주머니)
**배열에서 내가 원하는 것을 지우고 싶으면 값이 아니라 index를 알 것.
3. …
=> [박서진/remove-modify-todo-item]할 일 수정, 삭제 API 만들기, 수업 내용 정리

homework/han-minyeop/backend/app.js, homework/han-minyeop/backend/package.json, homework/han-minyeop/backend/yarn.lock
**TOKEN = 특정 규칙에 맡게 문자열** 
JWT => 인증에 필요한 정보들을 암호화시킨 JSON 토큰을 의미
JWT 기반 인증 => JWT 토큰을 HTTP 헤더에 실어 서버가 클라이언트를 식별하는 방식
JSON 데이터를 Base64 URL-safe Encode 를 통해 인코딩하여 직렬화한 것이며
토큰 내부에는 위변조 방지를 위해 개인키를 통한 전자서명도 들어있다
**JWT Process**
1. 사용자가 id와 password를 입력하여 로그인을 시도
2. 서버는 요청을 확인하고 secret key를 통해 Access token을 발급
3. JWT 토큰을 클라이언트에 전달
4. 클라이언트에서 API 을 요청할때  클라이언트가 Authorization header에 Access token을 담아서 보냄
5. 서버는 JWT Signature를 체크하고 Payload로부터 사용자 정보를 확인해 데이터를 반환
6. 클라이언트의 로그인 정보를 서버 메모리에 저장하지 않기 때문에 토큰기반 인증 메커니즘을 제공
인증이 필요한 경로에 접근할 때 서버 측은 Authorization 헤더에 유효한 JWT 또는 존재하는지 확인
**JWT 구조**
Header 에는 JWT 에서 사용할 타입과 해시 알고리즘의 종류가 담겨있으며
Payload 는 서버에서 첨부한 사용자 권한 정보와 데이터가 담겨있다
마지막으로 Signature 에는 Header, Payload 를 Base64 URL-safe Encode 를 한 이후 
Header 에 명시된 해시함수를 적용하고, Private Key로 서명한 전자서명이 담겨있다
**JWT …
=> [한민엽/auth] JWT에 대하여 / + 회원가입 기능 , 인증 기능 추가

homework/lee-yeonseo/backend/app.js
>미들웨어
컨트롤러의 앞이나 뒤에서 실행되는 함수.
에러 처리, 사용자 인증, 로그 기록 등의 다양한 용도로 사용된다.
사용시 장점
- 동일한 미들웨어를 여러 라우터에서 사용할 수 있고, 수정해야할 때  해당 미들웨어 하나만 수정하면 된다.
- 코드의 역할이 명확하게 구분되어 가독성이 높아진다.
>app.use(cors())
웹 브라우저에서 다른 출처의 리소스를 요청할 수 있게 해주는 보안 기능인 cors 미들웨어를 사용하기 위한 코드.
>강제로 에러를 발생시키는 법
```
throw new Error('에러 메시지')
```
>자주 쓰이는 함수 모듈화
- 동일한 기능을 여러 곳에 쉽게 재사용할 수 있다.
- 기능의 수정이 필요할 때 해당 모듈만 수정하면 된다.
- 코드의 가독성이 높아진다.
- 동일한 내용의 코드를 여러 곳에 작성할 필요가 없어져 코드의 중복을 방지할 수 있다.
미들웨어
함수 모듈화
throw new Error
=> [이연서/middleware] 미들웨어

homework/leegilhyeon/backend/app.js, homework/leegilhyeon/backend/package.json, homework/leegilhyeon/backend/yarn.lock
`JWT란?`
JWT(Json Web Token)는 웹에서 사용되는 JSON 형식의 토큰에 대한 표준 규격으로, 주로 사용자의 인증 또는 인가정보를 서버와 클라이언트간에 안전하게 주고 받기 위해 사용된다.
`JWT의 구조`
JWT는 헤더(header)와 페이로드(payload), 서명(signature) 세 부분으로 이루어지며 각 구역은 **.**으로 구분된다
- 헤더 : 토큰의 유형과 서명 알고리즘 명시
- 페이로드: 사용자의 인증/인가 정보
- 서명 : 헤더와 페이로드가 비밀키로 서명되어 저장됨
* JWT에서 자주 사용되는 JSON키
-sub : 인증주체(subject)
-iss : 토큰 발급처
-typ : 토큰의 유형
-alg : 서명 알고리즘
-iat : 발급시각
-exp : 만료시각
-aud : 클라이언트
`JWT 인증방식`
1. 클라이언트가 서버에 로그인을 요청한다.
2. 서버는 인증 절차를 수행하고 인증이 유효할시 JWT를 클라이언트에게 발급해준다.
3. 클라이언트는 요청시 요청헤더의 authorization에 발급 받은 JWT를 담아 보낸다.
4. 서버는 전달받은 JWT를 검증하고 응답한다. (JWT에 요청한 사용자 정보가 담겨있어 사용자 식별이 가능하다)
`JWT 장점`
- 서버가 사용자의 상태를 유지할 필요가 없어 서버는 무상태가 되어 서버의 자원을 절약하고 확장성을 향상 시킬 수 있다.
- 별도의 저장소를 갖지 않아도 된다.
- 토큰을 사용하는 다른 시스템에 접근 및 권한 공유가 가능하다
- 세션 사용이 불가능한 모바일에서도 사용 가능하다.
`JWT 단점`
- 많은 양의 데이터를 JWT에 …
=> [이길현/auth] 회원가입,로그인 api 작성 & jwt 발급과 검증

homework/han-minyeop/backend/app.js
splice() 메서드는 배열의 기존 요소를 삭제 또는 교체하거나 새 요소를 추가하여 배열의 내용을 변경
`**array.splice(start, deleteCount, item1, item2, ...)**`
start -> 배열의 변경을 시작할 인덱스  음수이면 배열의 끝에서부터 요소를 카운트
deleteCount -> 배열에서 제거할 요소의 수 0이면 요소를 제거하지 않음
item1, item2, ...: -> 배열에 추가할 요소들 이 매개변수를 생략하면 splice()는 요소를 제거하기만 한다
**삭제**
```
let array = [1, 2, 3, 4, 5];
let removed = array.splice(2, 2); // 인덱스 2부터 2개의 요소 제거
console.log(array); // [1, 2, 5]
console.log(removed); // [3, 4]
```
**추가**
```
let array = [1, 2, 3, 4, 5];
array.splice(2, 0, 'a', 'b'); // 인덱스 2에 'a', 'b' 추가
console.log(array); // [1, 2, 'a', 'b', 3, 4, 5]
```
**교체**
```
let array = [1, 2, 3, 4, 5];
array.splice(2, 2, 'a', 'b'); // 인덱스 2부터 2개의 요소를 'a', 'b'로 교체
console.log(array); // [1, 2, 'a', 'b', 5]
```
indexOf() 메서드는 배열에서 지정된 요소를 찾을 수 있는 첫 번째 인덱스를 반환하고, 요소가 …
=> [한민엽/remove-modify-todo-item] API 추가 기능 구현

homework/leegilhyeon/backend/app.js
[ 컨트롤러 ] 
컨트롤러는 웹 애플리케이션의 핵심 부분중 하나로 요청과 응답을 처리하는 역할을 담당한다. 클라이언트로부터 요청을 받으면, 해당 요청에 맞는 로직을 수행한 뒤 응답을 반환해 준다. 컨트롤러는 요청의 종류에 따라 여러 개의 컨트롤러 함수를 작성할 수 있다.
[ 미들웨어 ]
미들웨어는 요청과 응답 사이에서 실행되는 함수로 미들웨어는 순차적으로 실행되며, 컨트롤러 실행 전에 특정 작업을 수행하거나, 컨트롤러가 응답을 반환한 후 추가 작업을 수행할 수 있다. 주요 기능으로는 요청 및 응답 객체를 수정하거나, 인증 및 권한 확인, 에러 처리 등이 있다.
[ 에러 핸들링 미들웨어 ] 
에러 핸들링 미들웨어는 웹 애플리케이션에서 발생할 수 있는 예외나 오류를 처리하는 역할을 한다.
[ 메모 ]
* error 발생시키는 법
:  throw new Error("error 발생")
* 컨트롤러 뒤에 실행 시킬 미들웨어는 뒤에 위치시킨다.
*  app.use(express.json())
: express.json함수의 호출을 전역으로 사용할때 ( ) 을 넣어 사용한다.
error 발생, 
미들웨어 작성
=> [이길현/middleware] 미들웨어 작성해보기

homework/jeon-suwon/backend/app.js
사용자의 특정한 요구대로 만들어 제공하는 프로그램으로, 중간에서 조정과 중개의 역할을 수행하는 소프트웨어다.
- Express.js의 미들웨어는 HTTP 요청이 들어온 순간부터 순차적으로 시작이 된다.
- 미들웨어는 HTTP 요청과 응답 객체를 처리하거나, 다음 미들웨어를 실행할 수 있다.
- HTTP 응답이 마무리될 때까지 미들웨어 동작 사이클이 실행된다.
미들웨어는 애플리케이션 미들웨어, 라우터 미들웨어, 오류처리 미들웨어로 분류가 가능하고, 필요한 동작 방식에 따라서 미들웨어를 적용할 위치를 맞게 결정해야한다.
`app.use(express.json());
app.use((req, res, next) => {
console.log('모든 요청에서 다 실행 됩니다.')
next();
});
app.get('/', (req, res, next) => {
console.log('GET 요청에서만 실행됩니다.');
next();
}`
이와같이 app.use는 모든 요청에서 다 실행될 수있고,
app.get이나 put, post는 그 요청에 맞는 요청이 들어와야 실행이 되는것을 확인 할 수 있다.
app.use와 app.get의 차이
미들웨어의 순차적 동작사실
=> [전수원/middleware] 미들웨어정리

homework/hyunwoo/backend/app.js
[ 미들웨어 ]
• 서버가 요청을 받고 응답을 하는 사이에서 작동하는 코드
• 컨트롤러 실행 전에 특정 작업을 수행하거나 컨트롤러가 응답한 후 추가 작업을 실행하는
• 미들웨어와 컨트롤러를 나누는 것은 과정인지 결과인지가 중요
• 미들웨어는 원하는 결과로 가는 과정이기 때문에 next()를 통해 다음 미들웨어를 실행함
• 상단에 있는 미들웨어가 먼저 실행되기 때문에 작성 순서가 중요함
• 모든 router에서 미들웨어를 실행하려면 app.use(미들웨어)를 사용
[ 컨트롤러 ]
• 웹 에플리케이션에서 요청과 응답 사이의 로직을 처리
• 클라이언트로부터 요청을 받으면 로직을 수행한 뒤 응답을 반환
• 데이터베이스와의 상호작용이나 다른 API 통신 가능
• 주로 라우팅 파일에서 사용
[ 에러 처리 미들웨어 ]
• 미들웨어나 router에서 오류가 발생하는 경우 에러 메세지에 너무 많은 정보가 나올 수 있음
• 에러 내용에 대해 사용자가 이해하기 쉬운 간단한 메세지를 반환하는 방법
• app.use((err, req, res, next) => { } ) 형식으로 사용
[ 에러 발생시키기 ]
• throw new Error("에러가 발생했습니다.")
• 예외처리 상황에서 강제로 에러를 발생시키는 방법
반복되는 코드는 함수로 정리하기
감사합니다!
=> [이현우/middleware] 미들웨어 작성하여 리팩토링

homework/lee-yeonseo/backend/app.js, homework/lee-yeonseo/backend/controllers/todoItem.controller.js, homework/lee-yeonseo/backend/controllers/user.controller.js, homework/lee-yeonseo/backend/db/todoItems.js, homework/lee-yeonseo/backend/db/users.js, homework/lee-yeonseo/backend/middlewares/auth.middleware.js, homework/lee-yeonseo/backend/middlewares/errorHandling.middleware.js, homework/lee-yeonseo/backend/middlewares/todoItemIdValidator.middleware.js, homework/lee-yeonseo/exception.js
>3계층 아키텍쳐 패턴
- controller, service, repository로 구성된다.
- 코드의 유지보수와 확장성을 높일 수 있다.
- 초반 코드 작성 시 시간이 많이 들 수 있다.
>import & export 
- export
특정 변수, 함수, 객체 등을 다른 파일로 내보내는 역할
default로 내보낼 때는 import시 중괄호{}를 쓰지 않아도 된다.
- import
다른 파일에서 내보낸 변수, 함수, 객체 등을 가져오는 역할
특정 파일에 export된 모든 걸 가져오려면 import * as 별명 from 경로
> try...catch
자바스크립트에서 오류를 처리하기 위한 방법
코드 실행 중에 발생하는 오류를 잡아 처리할 수 있게 해준다.
- try
오류가 발생할 가능성이 있는 코드를 작성하는 곳.
오류가 발생하면 즉시 실행이 중단되고 catch 블록으로 넘어간다.
- catch
try 블록에서 오류가 생겼을 때 실행할 코드를 작성하는 곳
에러 객체를 통해 오류에 대한 정보를 얻을 수 있다.
- finally
오류 발생 여부와 관계없이 항상 실행되는 곳
3계층 아키텍처 패턴
import / export
try...catch
=> [이연서/refactoring] 3계층 아키텍쳐 패턴 / import&export / try...catch

homework/songsamuel/backend/app.js
1. 컴퓨터는 데이터를 저장한다. 그럴 때 저장 하는 곳을 우리는 "파일"이라고 칭한다.
2. app.get('/', <**_(req, res) => {
res.send('연습만이 살길이다.4')
}_**)> 
위 코드에서  <> 속에 있는 곳을 우리는 "컨트롤러"라고 칭한다.
3. 컨트롤러란 무엇인가? 
컨트롤러란 요청을 받아서 실제 요청에 따른 처리를 해주는 진입점을 칭한다.
4. 미들웨어란 무엇인가? 
미들웨어란 컨트롤런 전,후로 실행되는 기능들을 통칭해서 말 할 수 있다.
즉 내가 실제 구현해야 하는 기능 "전에!" 실행되는 애들 전부 미들웨어다.
내가 응답 보낸 "후에!" 하는 행위들 전부 미들웨어다.
대표적으로 자주보는 app.use(express.json())을 말 할 수 있다.
컨트롤러 전, 후로 실행되는 함수들 전부 미들웨어!
그렇다면 미들웨어와 컨트롤러를 나누는 조건이란 무엇인가? 
= express에서는 우리가 개념적으로 나눌 수 있다. 따라서 조금 많이 어렵다.
= **_내가 요청을 받은 행위를 하는 곳이 컨트롤러다._**
하지만 미들웨어에서는 다음으로 넘어가기 위해서 Next()를 꼭 붙인다.
미들웨어는 함수이다. 즉 함수는 밖에다 정의할 수 있다. 
= 전역 함수로 만들어버리고 가져다 쓸 수 있다.!
이걸 또 응용한 것이 에러처리 미들웨어다.
에러처리 미들웨어는 "즉 (req, res, next) ==> (err, req, res, next) " 앞에 err을 붙이면 에러가 발생 했을 때 에러처리 미들웨어로 들어오게 된다.
또한 에러처리 미들웨어 사용 …
=> [송사무엘/middleware] 미들웨어 작성 및 코드 변경

homework/hyunwoo/backend/app.js, homework/hyunwoo/backend/controller/user.controller.js, homework/hyunwoo/backend/controllers/todoItem.controller.js, homework/hyunwoo/backend/controllers/user.controller.js, homework/hyunwoo/backend/db/todoItems.js, homework/hyunwoo/backend/db/users.js, homework/hyunwoo/backend/middlewares/auth.middleware.js, homework/hyunwoo/backend/middlewares/errorHandler.middleware.js, homework/hyunwoo/backend/middlewares/levelLog.middleware.js, homework/hyunwoo/try-catch.js
< 3계층 아키텍처 패턴 >
- Controller: Router에서 클라이언트의 요청을 받아서 결과를 반환한다.
- Service: 데이터 가공으로 비즈니스 로직을 수행하여 클라이언트가 원하는 작업을 실행한다.
- Repository: Database에 접근하여 CRUD 작업을 실행한다.
- Controller -> Service -> Repositort -> Service -> Controller 순서로 진행된다.
- 에러처리 등 유지보수를 위해 아키텍처 패턴을 사용하여 효율성을 높일 수 있다.
< try... catch >
- try 안에 실행 내용이 들어오고 catch 안에는 try에서 에러발생 시 에러내용을 반환한다.
- 에러가 발생하는 경우 브라우저에 에러 내용과 함께  프로젝트의 구성이 나오는 경우가 있으므로
catch에는 전달하고 싶은 내용만 보이도록 작성한다.
try{
throw new Error // 일부러 에러를 발생시킨다.
} catch (e) {
console.log(e) // 에러 내용을 찍어볼 수 있다.
}
app.get("/", (req, res) => {
try {
throw new Error(); // 일부러 에러를 발생시킨다.
} catch (e) {
res.status(400).json({
message: "권한이 없습니다.", // 사용자에게 메세지만 전달한다.
});
console.log(e); // 에러 내용을 찍어볼 수 있다.
}
});
< 경로에 있는 모든 모듈 가져오기 >
import * as 'name' from '/경로'
< 하나의 모듈만 내보내기 > …
=> [이현우/refactoring]3Layered Architecture, try... catch 연습하기

homework/songsamuel/backend/app.js, homework/songsamuel/backend/controllers/todoitem.controller.js, homework/songsamuel/backend/controllers/user.controller.js, homework/songsamuel/backend/db/todoitems.js, homework/songsamuel/backend/db/users.js, homework/songsamuel/backend/middlewares/auth.Middleware.js, homework/songsamuel/backend/middlewares/leaveLogMiddleware.js
컨트롤러 = 라우터 안에 구현을 담당하는 함수 
레이어드 = 겹친 모습 
어째서 3LA라고 하는가?
이러한 모습 때문에 레이어드라고 칭한다.
3LA의 특징
장점 : 유지보수가 편하고 보기 좋다. 남들이 보기에 이해하기 쉽고 오류 찾기 편하다.
단점 : 초기에 제작할 때 어렵고 힘들긴 하다. 
어째서??? 그렇게 느끼는가? 
ex)
아파트 팬트리 수납장 -> 막 옷을 쌓으면 넣기는 하겠지만 필요할 때 딱 딱 꺼내서 하기 어렵다.
1. export/ import
당연한 것이지만 
불러오기(import) 하기 전에 
무조건 내보내기(export)를 먼저 해야 한다.
Import 할 때 {}를 왜 쓰냐?? 무슨 차이냐? 써야 할 때와 안 써야 할 때 언제냐?
안 써야 할 때 = export default를 쓸 때 즉 그 파일 전체를 import 할 때 안쓴다.
써야 할 때 = export로 여러 개를 내보내면 객체로 들어온다고 생각하면 된다.
< {} <-속에 들어가는 이름은 실제 export하는 곳에서 정해져 있는 이름이다. >
그 외에도 default를 안 쓰고 가져올 것인데 너무 많다!!
그러면 *(전체를 가져와라) as(어떤 이름으로?) 변수명으로 사용할 수 있다.
* as 변수명 <- 이렇게
3계층 아키텍처 패턴
import / export
try...catch
=> [송사무엘/refactoring] 3계층 아키텍처(3LA) & export/ import & try catch

homework/jinseo_kim/backend/.env.example, homework/jinseo_kim/backend/app.js, homework/jinseo_kim/backend/controllers/todoItems.controller.js, homework/jinseo_kim/backend/controllers/users.controller.js, homework/jinseo_kim/backend/repositories/todoItem.repository.js, homework/jinseo_kim/backend/repositories/user.repository.js, homework/jinseo_kim/backend/services/todoItem.service.js, homework/jinseo_kim/backend/services/user.service.js, homework/jinseo_kim/backend/validatetor/todoitemid.validatetor.js
- 3계층 구조 (3 Layered Architecture)
- service 계층
- repository 계층
- dotenv
req / res 그리고 database 와 직접적인 액세스를 하는 로직을 제외한 모든 로직들을 모아놓은 곳
```
// 할일 찾기
// 매개변수로 ID를 받아서 할일 찾기
export function getTodoItemById(id) {
// todoItemRepository의 findOneById 메서드를 실행하는데 ID 값을 매개변수로 준다.
// todoItem에는 반환받은 할일 객체가 들어있다.
const todoItem = todoItemRepository.findOneById(id);
// todoItem이 없으면 에러 던지기.
if (!todoItem) {
throw new Error('Todo item not found');
}
// 위의 로직을 패스할 경우 todoItem를 반환한다.
return todoItem;
}
```
req / res 그리고 데이터 처리, 밸리데이션 등과 같은 처리 로직을 제외한 database와 직접적인 액세스를 하는 로직을 모아놓은 곳
```
// 여러개 찾기
// userId를 매개변수로 받아서 할일 찾기
export function findMany(userId) {
// todoItemsFromDB에서 filter 메서드를 실행하는데 userId를 매개변수로 해서, userId 값이 일치하는 할일 객체를 반환한다.
return todoItemsFromDB.filter((todoItem) => todoItem.userId === …
```
=> [김진서/ref-service-repository] 3LA 적용 (service / repository) / dotenv(.env / .env.example)

homework/seojin/backend/app.js, homework/seojin/backend/controllers/todoItem.controller.js, homework/seojin/backend/controllers/user.controller.js, homework/seojin/backend/db/todoItems.js, homework/seojin/backend/db/users.js, homework/seojin/backend/middlewares/auth.middleware.js, homework/seojin/backend/middlewares/leaveLog.middleware.js, homework/seojin/backend/package.json, homework/seojin/backend/repositories/todoItem.repository.js, homework/seojin/backend/repositories/user.repository.js, homework/seojin/backend/services/todoItem.service.js, homework/seojin/backend/services/user.service.js, homework/seojin/backend/yarn.lock
먼저 아키텍쳐 패턴은 소프트웨어의 구조를 구성하기위한 가장 기본적인 토대를 제시합니다. 아키텍처 패턴은 각각의 시스템들과 그 역할이 정의되어 있고, 여러 시스템 사이의 관계와 규칙 등이 포함되어 있습니다. 장점으로 안정적인 개발이 가능하고, 유지보수 면에서 이점이 있습니다.
3 layerd architecture는 컨트롤러(controller), 서비스(service), 레파지토리(repository) 로 이루어진 아키텍쳐의 한 종류입니다.
1. 컨트롤러(Controller) : 어플리케이션의 가장 바깥 부분, 요청/응답을 처리
- 클라이언트의 요청(Request)을 수신 한 후 서버에서 처리된 결과를 반환(Response)해주는 역할을 담당합니다.
2. 서비스(Service) : 어플리케이션의 중간 부분, API의 핵심적인 동작이 많이 일어나는 부분
- 아키텍처의 가장 핵심적인 비즈니스 로직이 수행되는 부분입니다.
3. 저장소(Repository) : 어플리케이션의 가장 안쪽 부분, 데이터베이스와 맞닿아 있음.
- 실제 데이터베이스와 통신하는 계층입니다.
파일을 나누는 법
1. export(내보내기) 불러오기(import)를 통해 파일들을 연결
2. 유저 테이블(사용자 정보) 과 할 일 목록 테이블을 기준으로 파일을 나눔
3. 나눈 파일들을 3 레이어드 아키텍쳐 기준에 맞게 배열하기
3레이어드 아키텍쳐에 대한 이해와 export, import에 대한 심층적인 이해
3 layerd archtecture에 대한 내용을 따로 찾아 정리해봤습니다. 틀린 점이 있다면 말씀 부탁드립니다.
계속 생기는 오류를 잡느라 …
=> [박서진/refactoring] 3레이어드 아키텍쳐 분리하기

homework/jeon-suwon/lesson/12_class_router/class.js, homework/jeon-suwon/re-api/app.js, homework/jeon-suwon/re-api/common/custom.error.js, homework/jeon-suwon/re-api/controllers/todoitem.controller.js, homework/jeon-suwon/re-api/controllers/user.controller.js, homework/jeon-suwon/re-api/middleware/auth.middleware.js, homework/jeon-suwon/re-api/middleware/error.middleware.js, homework/jeon-suwon/re-api/repositories/todoitem.repository.js, homework/jeon-suwon/re-api/router/todoitem.rotuer.js, homework/jeon-suwon/re-api/router/user.router.js, homework/jeon-suwon/re-api/services/user.service.js, homework/jeon-suwon/re-api/validation/sign-in-validation.js
class를 이용한 커스텀 에러처리 error handling middleware 리팩토링
class 기초 연습
라우터 리팩토링
instanceof
class활용으로 에러처리 커스텀 
```
export class CustomError extends Error {
constructor(message, status) {
super(message);
this.status = status;
}
}
```
내보내기 후에 errorhandlingmiddleware파일에서 가져와서 작성한다.
```
import { CustomError } from "../common/custom.error.js";
export const errorMiddleware = (err, req, res, next) => {
if (err instanceof CustomError) {
console.error(err);
res.status(err.status).send({ message: err.message });
} else {
console.error(err);
res.status(500).send({ message: "Internal Server Error" });
}
};
```
**### class 활용**
//클래스 객체 생성
```
class Pet {
constructor(name, age, gender = "male") {
// gender = "male" << 이런식으로하면 입력하지않으면 male 자동으로 입력가능
console.log("IN PET CONSTRUCTOR!");
this.name = name; …
```
=> [전수원/class-router] class 커스텀 에러 / class 연습/ 라우터 리팩토링

homework/songsamuel/backend/app.js, homework/songsamuel/backend/class.practice.js, homework/songsamuel/backend/common/custom.error.js, homework/songsamuel/backend/controllers/todoitem.controller.js, homework/songsamuel/backend/controllers/user.controller.js, homework/songsamuel/backend/middlewares/errorMiddleware.js, homework/songsamuel/backend/repositories/user.repository.js, homework/songsamuel/backend/router/todoItems.router.js, homework/songsamuel/backend/router/user.router.js, homework/songsamuel/backend/services/todoitem.service.js, homework/songsamuel/backend/services/user.service.js
class란 특정 객체를 생성하기 위해 변수와 메소드를 정의하는 일종의 **틀**이다.
이 class 안에는 constructor란 생성자가 존재한다.
constructor를 실행하는 방법은 객체를 생성할 때 처럼
[new 붕어빵 (~~~)] 의 모습을 할 때 ~~~에 값을 넣으면 자동 실행이 된다. 
예시)
class Animal {
constructor(name) {
this.name = name;
}
}
=>  const anyAnimal = new Animal("사자"); 
이렇게 class속에 있는 constructor를 이용하여 새로운(New)를 객체를 생성 할 수 있다.
상속
상속이란 class에서 상위 클래스의 내용을 받은 것으로 누가 상위 클래스인지 알려면 아래와 같이 class 옆에 작성된다.
예) class Cat **_extends Animal_**
상속 받은 class(Cat)은 상속을 해준 class(Animal)의 constructor 내용을 상속 받게 되고 이를 super라고 명시하게 된다.
예시)
class Animal {
**constructor(name)** {
this.name = name;
}
}
class Cat extends Animal {
_**constructor(name, color)**_ {
_**super(name)**;_
this.color == color;
}
}
이렇게 상속 받은 class는 상속 해준 class의 기능 또한 사용할 수 있게 된다.
라우터
라우터란?   api의 경로를 해당 요청의 컨트롤러로 연결해주는 역할
같은 라우터 파일에 있는 …
=> [송사무엘/class-router] class 연습 및 개념 / 커스텀 에러 제작 

homework/lee-yeonseo/backend/common/conn.js, homework/lee-yeonseo/backend/repositories/todoItem.repository.js, homework/lee-yeonseo/backend/repositories/user.repository.js, homework/lee-yeonseo/backend/services/todoItem.service.js
>쿼리 인젝션
사용자의 입력을 직접적으로 쿼리에 포함시키는 경우, 경로에 sql쿼리를 삽입하여 데이터베이스를 조작할 수 있기 때문에 보안이 취약해진다.
>쿼리 인젝션 방어 방법
- sql쿼리와 파라미터를 분리한다.
```
const sql = `SELECT * FROM todo_items WHERE user_id = ?`;
const [myTodoItems] = await conn.execute(sql, [userId]);
```
- 파라미터 바인딩
```
const sql = `INSERT INTO todo_items (user_id, title) VALUES (:userId, :title)`;
const [newTodoItem] = await conn.execute(sql, { userId, title });
```
여러가지 데이터를 전달할 때 가독성을 위해서 쓰는 방법
객체로 전달해야한다.
```
export default await mysql.createConnection({
host: process.env.DB_HOST,
user: process.env.DB_USER,
password: process.env.DB_PASSWORD,
database: process.env.DB_DATABASE,
namedPlaceholders: true, //이거
});
```
db 연결하는 부분에 namedPlaceholders: true 를 추가해야한다.
쿼리인젝션
=> [이연서/protect-sql-injection] 쿼리 인젝션

homework/hyunwoo/backend/app.js, homework/hyunwoo/backend/common/custom.error.js, homework/hyunwoo/backend/controllers/user.controller.js, homework/hyunwoo/backend/middlewares/errorHandler.middleware.js, homework/hyunwoo/backend/repositories/todoItem.repository.js, homework/hyunwoo/backend/repositories/user.repository.js, homework/hyunwoo/backend/routers/todoItem.router.js, homework/hyunwoo/backend/routers/user.router.js, homework/hyunwoo/backend/services/todoItem.service.js, homework/hyunwoo/backend/services/user.service.js, homework/hyunwoo/class.js
[ ErrorHandler ]
- 각 함수마다 에러코드를 작성할 경우 중복되는 코드가 많아진다.
- 중복되는 코드를 줄이고 에러처리를 한군데에서 관리할 수 있는 방법이 에러핸들링이다.
- CustomError를 설정하여 에러메세지와 상태코드를 반환할 수 있다.
[ Router ]
- URL 경로를 파악하기 쉽게 분리하여 관리할 수 있다.
- 엔드포인트와 해당 포인트에서 실행되어야 할 로직을 연결하는 역할
[ Class ]
- 클래스는 객체지향 프로그래밍의 핵심 구성요소로 객체를 만들기 위한 틀
- 속성과 객체가 있는데 객체는 클래스를 기반으로 생성되면 instance라고 한다.
- 속성은 객체의 성질을 결정하고, 메서드는 객체의 성질을 변화시키거나 기능을 사용한다.
- 클래스는 붕어빵의 틀, 객체는 붕어빵, 속성은 붕어빵의 속재료, 메서드는 붕어빵의 속재료나 상태를 변경하는 것
- class 키워드를 사용하여 속성과 메서드를 정의하고 new 키워드를 사용하여 객체를 생성한다.
에러핸들링을 하는 이유, 클래스의 사용방법
감사합니다!
=> [이현우/class-router] ErrorHandler, Router, Class 연습하기

homework/jinseo_kim/backend/app.js, homework/jinseo_kim/backend/common/custom.error.js, homework/jinseo_kim/backend/controllers/todoItems.controller.js, homework/jinseo_kim/backend/middlewares/errorHandler.middleware.js, homework/jinseo_kim/backend/repositories/todoItem.repository.js, homework/jinseo_kim/backend/routers/todoItem.router.js, homework/jinseo_kim/backend/routers/user.router.js, homework/jinseo_kim/backend/services/todoItem.service.js, homework/jinseo_kim/backend/services/user.service.js, homework/jinseo_kim/practice/class.js
- CLASS 연습
- 붕어빵, 붕빵, 빵 연습
- 에러 핸들러 개편
- 커스텀 에러 띄우는 방법
- 라우터 나누기 및 실행
- CLASS 는 붕어빵 틀, 자동차 프레임 틀  같은 느낌으로, 속재료를 채워 넣어서 인스턴스를 만들어서 활용한다.
- 커스텀 에러 / 에러 핸들러를 통해 ```oops, An error occurred on the server . . .``` 에러 이외에, 상황에 적절한 에러를 선언하고 출력함
- 각각 기능별로 중복되는 주소 및 엔드인트를 찾고, 중복되는 주소를 라우터로 나눠줌!
=> [김진서/class-router] CLASS 붕어빵, 빵 연습 / 에러 핸들러 개편 / 라우터 나누기

homework/lee-yeonseo/backend/common/conn.js, homework/lee-yeonseo/backend/common/prisma.js, homework/lee-yeonseo/backend/package.json, homework/lee-yeonseo/backend/prisma/schema.prisma, homework/lee-yeonseo/backend/repositories/todoItem.repository.js, homework/lee-yeonseo/backend/repositories/user.repository.js, homework/lee-yeonseo/backend/services/todoItem.service.js, homework/lee-yeonseo/backend/yarn.lock
>프리즈마
- 데이터베이스 ORM 도구로, 데이터베이스와의 상호작용을 쉽게 할 수 있도록 도와준다.
- PostgresSQL, MySQL, SQLite 등 여러 데이터베이스를 지원한다.
>프리즈마 스키마 정의
- @map()으로 db상에서 사용될 이름을 정해줄 수 있다. (@ 한 개는 컬럼, 두 개는 테이블)
>프리즈마 로그 찍는 법
```
import { PrismaClient } from '@prisma/client'
export default new PrismaClient({
log: ['query', 'info', 'warn', 'error'],
})
```
=> [이연서/prisma] prisma 연결

homework/najiyoon/backend/common/prisma.js, homework/najiyoon/backend/package.json, homework/najiyoon/backend/prisma/schema.prisma, homework/najiyoon/backend/repository/todoitems.repository.js, homework/najiyoon/backend/repository/users.repository.js, homework/najiyoon/backend/service/todoitems.service.js, homework/najiyoon/backend/yarn.lock
```mysql -> prisma```
이미 DB에 테이블이 존재할 경우에는
yarn add prisma -> npx prisma -> prisma client 파일 생성 -> npx prisma init
.env 에 data base 정보 작성 (provider-> mysql) -> npx prisma db pull ->
yarn add @prisma/client -> npx prisma generate
만약 기존 테이블을 날리고 싶다면 npx prisma db push --force-reset
```DBMS```
: 데이터베이스 관리 시스템 - (MySQL, PostgresQL, MS-SQL, Oracle 등.. 그걸 편리하게 사용하게 해주는 prisma) 
Orm : 필드명 테이블 명을 변경해서 디비에 요청 => 우리가 테이블과 필드명을 굳이 하지 않아도 됨 (프리즈마 : ORM중 하나)
;
1. 설계를 orm이 알 수 있도록 동기화 해야함 => 디비에 있는 것을 orm에 알려주는 것 
2. 프리즈마로 설계문서(청사진) 대로 디비에 반영할 것 => 자동으로  결국 디비에 있는 것을 내 orm에게 동기화 할 수 있도록 하는 것과 2번 방법이 다름 
=> orm과 디비를 동기화 해야함
기존의 db에 테이블 있을 경우에는 npx prisma db pull를 활용할 수 있음 .
.
.
=> [나지윤/homework/najiyoob-prisma] prisma 적용하기

homework/jinseo_kim/backend/.env.example, homework/jinseo_kim/backend/common/conn.js, homework/jinseo_kim/backend/constants/env.constant.js, homework/jinseo_kim/backend/controllers/todoItems.controller.js, homework/jinseo_kim/backend/controllers/users.controller.js, homework/jinseo_kim/backend/middlewares/errorHandler.middleware.js, homework/jinseo_kim/backend/repositories/todoItem.repository.js, homework/jinseo_kim/backend/repositories/user.repository.js, homework/jinseo_kim/backend/routers/todoItem.router.js, homework/jinseo_kim/backend/services/todoItem.service.js, homework/jinseo_kim/backend/services/user.service.js
기존의 todoItems.js DB를 MySQl로 대체 한 후, RAW QUERY문을 사용하여 DB에 직접 상호작용 하도록 변경 하였습니다.
▼ [POST] 할일 등록 
▼ [DELETE] 할일 삭제
어렵군용... 
raw query 문을 좀더 연습해봐야 될거 같아요 ㅠㅠ.
=> [김진서/beginning-of-db-sql-injection] MySQL 연결, raw query

homework/leegilhyeon/backend/controllers/todoItem.controller.js, homework/leegilhyeon/backend/controllers/user.controller.js, homework/leegilhyeon/backend/repository/todoItem.repository.js, homework/leegilhyeon/backend/repository/user.repository.js, homework/leegilhyeon/backend/services/todoItem.service.js
[ 쿼리 인젝션 ]
- 쿼리 인젝션은 말 그대로 쿼리안에 코드를 주입한다는 뜻으로 데이터베이스 쿼리에 악의적인 SQL 코드를 주입하여 데이터베이스에 담긴 데이터를 열람하거나 수정, 삭제 할 수 있게된다.
-예시 
`SELETE*FROM users WHERE id = 1` users 테이블에서 id가 1인 사용자만 조회하는 코드에 `or id is not null; ` 를 주입하여 모든 사용자 정보를 다 조회되게 해버린다.
-인젝션 방지
쿼리안에 변수를 직접 주입하지 않는다. 
예시코드1
```
export async function pushUser(newUser) {
const sql = `INSERT INTO users (email, password, name, role ) VALUES (${newUser.email}, ${newUser.password}, ${newUser.name}, ${newUser.role })`
const result = await conn.execute(sql)
```
방지1 
```
export async function pushUser(newUser) {
const sql = `INSERT INTO users (email, password, name, role ) VALUES (?, ?, ?, ?)`
const result = await conn.execute(sql,[newUser.email, newUser.password, newUser.name, newUser.role])
```
방지2 
```
export async function pushUser(newUser) { …
```
=> [이길현//protect-sql-injection] todoitem 리팩토링, 쿼리 인젝션

homework/hyunwoo/backend/.env.example, homework/hyunwoo/backend/app.js, homework/hyunwoo/backend/common/conn.js, homework/hyunwoo/backend/controllers/todoItem.controller.js, homework/hyunwoo/backend/controllers/user.controller.js, homework/hyunwoo/backend/middlewares/auth.middleware.js, homework/hyunwoo/backend/package.json, homework/hyunwoo/backend/repositories/todoItem.repository.js, homework/hyunwoo/backend/repositories/user.repository.js, homework/hyunwoo/backend/services/todoItem.service.js, homework/hyunwoo/backend/services/user.service.js, homework/hyunwoo/backend/yarn.lock
users, todo_items 테이블 DB 연결완료 및 쿼리문 작성했습니다.
[ SQL vs NoSQL ]
< SQL의 장점 >
- 명확하게 정의 된 스키마, 데이터 무결성 보장
- 관계는 각 데이터를 중복없이 한번만 저장
< SQL의 단점 >
- 상대적으로 덜 유연함
- 데이터 스키마는 사전에 계획되고 알려져야함
(나중에 수정하기가 번거롭거나 불가능 할 수 도 있음)
- 관계를 맺고 있기 때문에, JOIN문이 많은 매우 복잡한 쿼리가 만들어 질 수 있음
- 수평적 확장이 어렵고, 대체로 수직적 확장만 가능함
- 어떤 시점에서 (처리 할 수 있는 처리량과 관련하여) 성장 한계에 직면하게 됨
< NoSQL의 장점 >
- 스키마가 없기 때문에, 훨씬 더 유연함
- 언제든지 저장된 데이터를 조정하고 새로운 필드를 추가 할 수 있음
- 데이터는 애플리케이션이 필요로 하는 형식으로 저장되고, 이렇게 하면 데이터를 읽어오는 속도가 빨라짐
- 수직 및 수평 확장이 가능하므로 데이터베이스가 애플리케이션에서 발생시키는 모든 읽기 / 쓰기 요청을 처리 할 수 있음
< NoSQL의 단점 >
- 유연성 때문에, 데이터 구조 결정을 하지 못하고 미루게 될 수 있음
- 데이터 중복은 여러 컬렉션과 문서가 여러 개의 레코드가 변경된 경우 업데이트를 해야함
- 데이터가 여러 컬렉션에 중복되어 있기 때문에, 수정(update)를 해야 하는 경우 모든 컬렉션에서 수행해야 함
[ 쿼리 스트링 ]
< 검색 >
``` SELECT 컬럼명 * FROM 테이블 WHERE 조건 
< 이메일로 회원 조회 >
SELECT * FROM users …
```
=> [이현우/beginning-of-db-sql-injection] DB연결 및 SQL, 쿼리 인젝션

homework/songsamuel/backend/controllers/todoitem.controller.js, homework/songsamuel/backend/controllers/user.controller.js, homework/songsamuel/backend/middlewares/auth.Middleware.js, homework/songsamuel/backend/repositories/todoitem.repository.js, homework/songsamuel/backend/repositories/user.repository.js, homework/songsamuel/backend/services/todoitem.service.js, homework/songsamuel/backend/services/user.service.js
- 쿼리 인젝션이란?
[ ]  악의적인 사용자가 응용 프로그램의 데이터베이스와 상호 작용하는 쿼리를 조작하여, 데이터베이스에 대한 부적절한 접근을 시도하는 공격 기법입니다. 여기서 "쿼리"란 데이터베이스에 대해 수행되는 SQL 명령문을 의미합니다.
쿼리 예시1
```
SELECT * FROM users WHERE username = 'admin' AND password = 'password123';
```
- 쿼리는 users 테이블에서 username이 'admin'이고 password가 'password123'인 행을 조회합니다.
이런 것에서도 해킹이 가능하다. 예를 들어 아래의 코드로 작성하면 모든 user에 대한 데이터가 다 조회된다.
해킹 된 쿼리 예시 1
```
SELECT * FROM users WHERE username = 'admin' AND password = 'password123' or id is not null  
```
따라서 쿼리 인젝션이라는 것을 통해서 해킹을 방지한다.
해킹 예방 쿼리 예시 1
```
const query = `SELECT * FROM users WHERE username = ? AND password = ?`;
db.execute(query, [username, password]);
```
이런 식으로 코드를 작성하면 모든 users에 대한 데이터 조회를 예방 할 수 있다.
DB에서 데이터를 찾을 때는 async await를 붙이도록 하고 한번 붙인 코드와 연관된 코드들 또한 붙이도록 한다.
=> [송사무엘/protect-sql-injection] todoitem 리팩토링, 쿼리 인젝션, 테스트 완료

homework/najiyoon/backend/prisma/schema.prisma
```Index```
인덱스(Index)는 데이터베이스에서 테이블의 검색 속도를 높이기 위한 기술 또는 장치이다.(인덱스는 일반적으로 키(Key)와 값(Value)으로 구성)
장점 : 중복데이터 제거, 데이터 정렬 
단점 : 생성시간 소요, 데이터 공간차지, 추가작업의 필요성
(인덱스를 일부분만 설정하는 이유 : 저장공간을 많이 사용한다. / 수정할 때 편함 
; 인덱스 키를 다 일일히 지정해주면 아이디를 활용해서 해당 정보를 가져올 수 있는데 정보마다 인덱스를 넣으면 수정할 때 번거로워진다.)
+ 데이터의 양이 적으면 적을수록 효율을 내기 힘들다
```Fk```
외래키는 두 테이블 간의 관계 생성하는 열.  외래키 목적은 데이텉 무결성 유지하고, 두 인스턴스 간 탐색 허용 하는 것. 두 테이블간의 상호참조 역할함. 
프라이머리 키(: 기본키)는 인덱스 할 수 있으나 , foreign key 또한 인덱스 기능 할 수 있음.
컬럼으로도 찾을 수 있음. 관계형 데이터베이스의 테이블 간 관계를 정의하는 중요한 개념
외래키는 여러값 허용 가능. 
```enum```
: 보통 도메인을 설계할 때 사용하는 인스턴스의 수가 정해져 있고 관련된어 처리할 수 있는 상수값이 여러개 존재할 때 Enum을 사용
흔히 정해둔 내에서 선택할 수 있는 것
예시 . 
enum Role {
USER
ADMIN
}
Self relation :한 테이블 안에 id 와 self id 
추천인 기능 일때 : 추천인이란 가입된 유저… 즉 유저 아이디에서 선택하는 것이므로
```선택사항```
.
.
=> [나지윤/db-relation] db relation 설정 및 정리

homework/lee-yeonseo/backend/middlewares/auth.middleware.js, homework/lee-yeonseo/backend/prisma/schema.prisma
> prisma relation
- @relation을 사용하여 모델 간 관계를 설정할 수 있음
- 스키마에 변화가 있다면 npx prisma generate를 해준다.
- onDelete를 사용해서 참조하는 데이터가 삭제되었을 때, 같이 삭제되도록 설정 가능
> enum
- 미리 정의된 값들의 집함으로, 특정 컬럼의 값을 제한된 옵션 중에서만 선택 가능하도록 함
> index
- 데이터 검색 속도 향상을 위해 사용
- 일반적으로 자주 조회되는 컬럼에 설정
- unique를 가진 컬럼은 자동으로 인덱스가 생성
> key 와 index
- pk와 fk는 자동으로 unique index가 생성
=> [이연서/db-relation] relation, index, enum

homework/jinseo_kim/backend/.gitignore, homework/jinseo_kim/backend/common/prisma.js, homework/jinseo_kim/backend/package.json, homework/jinseo_kim/backend/prisma/schema.prisma, homework/jinseo_kim/backend/readme - prisma.md, homework/jinseo_kim/backend/repositories/todoItem.repository.js, homework/jinseo_kim/backend/repositories/user.repository.js, homework/jinseo_kim/backend/services/todoItem.service.js, homework/jinseo_kim/backend/yarn.lock
- 프리즈마는 데이터베이스 ORM(Object-Relational Mapping) 도구이다.
- 스키마를 통해 데이터베이스 모델을 정의한다.
- 프리즈마를 설치하고 나의 코드에 적용하는 방법.
- 프리즈마가 raw query 를 주고 받는 방법
- DATABASE와 CRUD 등의 상호작용을 쉽게 할 수 있도록 도와주는 ORM 도구 이다. 프레임워크나 라이브러리, 서비스 등이 아니다.
- 프리즈마는 SCHEMA 를 통해 데이터베이스의 구조와 모델을 정의하고, 이를 기반으로 DATABASE와 상호작용 한다.
이 단계는, 프로젝트 초기부터 PRISMA 를 사용하기로 하고, SCHEMA 를 정의하여 DATABASE에 PUSH 하는 과정입니다.
이와같은 과정을 통해 prisma schema 에 정의한 구조를 DATABASE에 적용합니다.
프로젝트 중간 단계에서 ORM도구를 변경하거나, 이미 DATABASE가 정의되어 있다면 이와같은 과정을 통해 DATABASE의 구조를 prisma schema 에 적용합니다.
```diff
// sh
+ // prisma 및 @prisma/client 를 통해 qurey 를 주고 받는 도구를 설치한다.
yarn add prisma @prisma/client
+ // prisma 를 초기화 하고, schema 와 .env 의 접속정보를 자동으로 작성한다. ( 내용 수정은 필수 ! )
prisma init
+ // 이미 DATABASE 가 설계되어 있고, 사용중이라면 pull을 통해 DB에서 데이터구조를 읽어온다.
npx prisma db pull
+ // DATABASE가 설계되어 …
```
=> [김진서/prisma] PRISMA 리펙토링 및 개념 정리

homework/jinseo_kim/backend/api-test.yml, homework/jinseo_kim/backend/package.json, homework/jinseo_kim/backend/result.json, homework/jinseo_kim/backend/result.json.html, homework/jinseo_kim/backend/yarn.lock
duration 30, arrivalrate 15, 450 count 테스트 완료
=> [김진서/artillery] 부하 테스트 완료 450 count

homework/songsamuel/backend/report.html, homework/songsamuel/backend/test.json, homework/songsamuel/backend/test.yaml
=> [송사무엘/artillery] 부하 테스트 완료

homework/hyunwoo/backend/package.json, homework/hyunwoo/backend/yarn.lock, homework/hyunwoo/report.html, homework/hyunwoo/test.json, homework/hyunwoo/test.yaml
=> [이현우/artillery]부하테스트 진행
